### ISSUE TITLE
A name error bug in InterventionSIR.py

### ISSUE THREAD

**Issue by JarvisOrange** [dylanhmorris/optimal-sir-intervention#1]
Hello, I think you guys just made a spelling mistake on line 120 in   InterventionSIR.py.
The name of variable should be first_timestep_error instead of fist_timestep_error.

**Comment by dylanhmorris** [comment]
Good catch, thanks! Now fixed by [a61618e](https://github.com/dylanhmorris/optimal-sir-intervention/commit/a61618ea2279761617edfbe47ddde192951ab707)
